//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanbanBoard.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Column.
        /// </summary>
        public static string Board_NewColumnName {
            get {
                return ResourceManager.GetString("Board_NewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Board_NewItemName {
            get {
                return ResourceManager.GetString("Board_NewItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brd.
        /// </summary>
        public static string BoardFileExtension {
            get {
                return ResourceManager.GetString("BoardFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ColumnName_Done {
            get {
                return ResourceManager.GetString("ColumnName_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string ColumnName_InProgress {
            get {
                return ResourceManager.GetString("ColumnName_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ColumnName_New {
            get {
                return ResourceManager.GetString("ColumnName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;body={0}.
        /// </summary>
        public static string Crash_Email_Body {
            get {
                return ResourceManager.GetString("Crash_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:stacketbugs@gmail.com?.
        /// </summary>
        public static string Crash_Email_MailTo {
            get {
                return ResourceManager.GetString("Crash_Email_MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject=Stacket Bug Report - Version {0}.
        /// </summary>
        public static string Crash_Email_Subject {
            get {
                return ResourceManager.GetString("Crash_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacket has encountered and error and has had to close. Should an error report be sent to the developers?.
        /// </summary>
        public static string Crash_Message {
            get {
                return ResourceManager.GetString("Crash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last column and cannot be removed..
        /// </summary>
        public static string Dialog_CannotRemoveLastColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_CannotRemoveLastColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board {0} is missing..
        /// </summary>
        public static string Dialog_MissingBoard_Message {
            get {
                return ResourceManager.GetString("Dialog_MissingBoard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Board File.
        /// </summary>
        public static string Dialog_MissingBoard_Title {
            get {
                return ResourceManager.GetString("Dialog_MissingBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for the new board:.
        /// </summary>
        public static string Dialog_NewBoard_Message {
            get {
                return ResourceManager.GetString("Dialog_NewBoard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Board.
        /// </summary>
        public static string Dialog_NewBoard_Title {
            get {
                return ResourceManager.GetString("Dialog_NewBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this column?.
        /// </summary>
        public static string Dialog_RemoveColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_RemoveColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove column.
        /// </summary>
        public static string Dialog_RemoveColumn_Title {
            get {
                return ResourceManager.GetString("Dialog_RemoveColumn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this item?.
        /// </summary>
        public static string Dialog_RemoveItem_Message {
            get {
                return ResourceManager.GetString("Dialog_RemoveItem_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string Dialog_RemoveItem_Title {
            get {
                return ResourceManager.GetString("Dialog_RemoveItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to the current board?.
        /// </summary>
        public static string Dialog_SaveChanges_Message {
            get {
                return ResourceManager.GetString("Dialog_SaveChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Dialog_SaveChanges_Title {
            get {
                return ResourceManager.GetString("Dialog_SaveChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should all the items within the column be saved? If so they will be moved to the leftmost column..
        /// </summary>
        public static string Dialog_SaveItemsInColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_SaveItemsInColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should Stacket start on Windows startup?.
        /// </summary>
        public static string Dialog_Startup_Message {
            get {
                return ResourceManager.GetString("Dialog_Startup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string FontIcon_Add {
            get {
                return ResourceManager.GetString("FontIcon_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FontIcon_Bin {
            get {
                return ResourceManager.GetString("FontIcon_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string FontIcon_Brush {
            get {
                return ResourceManager.GetString("FontIcon_Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string FontIcon_Close {
            get {
                return ResourceManager.GetString("FontIcon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string FontIcon_Comment {
            get {
                return ResourceManager.GetString("FontIcon_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string FontIcon_DownArrow {
            get {
                return ResourceManager.GetString("FontIcon_DownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string FontIcon_Download {
            get {
                return ResourceManager.GetString("FontIcon_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string FontIcon_LeftArrow {
            get {
                return ResourceManager.GetString("FontIcon_LeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string FontIcon_Lock {
            get {
                return ResourceManager.GetString("FontIcon_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        public static string FontIcon_New {
            get {
                return ResourceManager.GetString("FontIcon_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string FontIcon_Off {
            get {
                return ResourceManager.GetString("FontIcon_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string FontIcon_On {
            get {
                return ResourceManager.GetString("FontIcon_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        public static string FontIcon_Open {
            get {
                return ResourceManager.GetString("FontIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string FontIcon_Pin {
            get {
                return ResourceManager.GetString("FontIcon_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string FontIcon_Question {
            get {
                return ResourceManager.GetString("FontIcon_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string FontIcon_RightArrow {
            get {
                return ResourceManager.GetString("FontIcon_RightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string FontIcon_Settings {
            get {
                return ResourceManager.GetString("FontIcon_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string FontIcon_Uncomment {
            get {
                return ResourceManager.GetString("FontIcon_Uncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string FontIcon_Unlock {
            get {
                return ResourceManager.GetString("FontIcon_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string FontIcon_Unpin {
            get {
                return ResourceManager.GetString("FontIcon_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string FontIcon_UpArrow {
            get {
                return ResourceManager.GetString("FontIcon_UpArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacket.
        /// </summary>
        public static string Stacket {
            get {
                return ResourceManager.GetString("Stacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run.
        /// </summary>
        public static string StartupRegistryLocation {
            get {
                return ResourceManager.GetString("StartupRegistryLocation", resourceCulture);
            }
        }
    }
}
