//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanbanBoard.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Column.
        /// </summary>
        public static string Board_NewColumnName {
            get {
                return ResourceManager.GetString("Board_NewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Board_NewItemName {
            get {
                return ResourceManager.GetString("Board_NewItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brd.
        /// </summary>
        public static string BoardFileExtension {
            get {
                return ResourceManager.GetString("BoardFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ColumnName_Done {
            get {
                return ResourceManager.GetString("ColumnName_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string ColumnName_InProgress {
            get {
                return ResourceManager.GetString("ColumnName_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ColumnName_New {
            get {
                return ResourceManager.GetString("ColumnName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;body={0}.
        /// </summary>
        public static string Crash_Email_Body {
            get {
                return ResourceManager.GetString("Crash_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:stacketbugs@gmail.com?.
        /// </summary>
        public static string Crash_Email_MailTo {
            get {
                return ResourceManager.GetString("Crash_Email_MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject=Stacket Bug Report - Version {0}.
        /// </summary>
        public static string Crash_Email_Subject {
            get {
                return ResourceManager.GetString("Crash_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacket has encountered and error and has had to close. Should an error report be sent to the developers?.
        /// </summary>
        public static string Crash_Message {
            get {
                return ResourceManager.GetString("Crash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last column and cannot be removed..
        /// </summary>
        public static string Dialog_CannotRemoveLastColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_CannotRemoveLastColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board {0} is missing..
        /// </summary>
        public static string Dialog_MissingBoard_Message {
            get {
                return ResourceManager.GetString("Dialog_MissingBoard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Board File.
        /// </summary>
        public static string Dialog_MissingBoard_Title {
            get {
                return ResourceManager.GetString("Dialog_MissingBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board title already in use..
        /// </summary>
        public static string Dialog_NewBoard_Error {
            get {
                return ResourceManager.GetString("Dialog_NewBoard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for the new board:.
        /// </summary>
        public static string Dialog_NewBoard_Message {
            get {
                return ResourceManager.GetString("Dialog_NewBoard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Board.
        /// </summary>
        public static string Dialog_NewBoard_Title {
            get {
                return ResourceManager.GetString("Dialog_NewBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this board?.
        /// </summary>
        public static string Dialog_RemoveBoard_Message {
            get {
                return ResourceManager.GetString("Dialog_RemoveBoard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove board.
        /// </summary>
        public static string Dialog_RemoveBoard_Title {
            get {
                return ResourceManager.GetString("Dialog_RemoveBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this column?.
        /// </summary>
        public static string Dialog_RemoveColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_RemoveColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove column.
        /// </summary>
        public static string Dialog_RemoveColumn_Title {
            get {
                return ResourceManager.GetString("Dialog_RemoveColumn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to the current board?.
        /// </summary>
        public static string Dialog_SaveChanges_Message {
            get {
                return ResourceManager.GetString("Dialog_SaveChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Dialog_SaveChanges_Title {
            get {
                return ResourceManager.GetString("Dialog_SaveChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should all the items within the column be saved? If so they will be moved to the leftmost column..
        /// </summary>
        public static string Dialog_SaveItemsInColumn_Message {
            get {
                return ResourceManager.GetString("Dialog_SaveItemsInColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should Stacket start on Windows startup?.
        /// </summary>
        public static string Dialog_Startup_Message {
            get {
                return ResourceManager.GetString("Dialog_Startup_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stacket.
        /// </summary>
        public static string Stacket {
            get {
                return ResourceManager.GetString("Stacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run.
        /// </summary>
        public static string StartupRegistryLocation {
            get {
                return ResourceManager.GetString("StartupRegistryLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #&amp;&lt;NEWITEM&gt;&amp;#.
        /// </summary>
        public static string NewItemBreak
        {
            get
            {
                return ResourceManager.GetString("NewItemBreak", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to $%&lt;NEWITEMDATA&gt;%$.
        /// </summary>
        public static string NewItemData
        {
            get
            {
                return ResourceManager.GetString("NewItemData", resourceCulture);
            }
        }
    }
}
